version: "3.8"

services:
  backend:
    build:
      context: ./qb-back
    ports:
      - "8000:8000"
    volumes:
      - ./qb-back/app:/code/app
    env_file:
      - ./qb-back/.env
    depends_on:
      - db

  frontend:
    build:
      context: ./qb-front
    ports:
      - "5173:5173"
    env_file:
      - ./qb-front/.env

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: